// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCToky06NbY6OQflvzFpPj2gpgJm5Wi3Gw',
    appId: '1:796044680835:web:37f0408bea82dd924d45b6',
    messagingSenderId: '796044680835',
    projectId: 'fluttertest-c773f',
    authDomain: 'fluttertest-c773f.firebaseapp.com',
    storageBucket: 'fluttertest-c773f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9IgkYCKRyTUJNrgfWhZ48ZnP_E-b87gs',
    appId: '1:796044680835:android:396ab1a1b949c4254d45b6',
    messagingSenderId: '796044680835',
    projectId: 'fluttertest-c773f',
    storageBucket: 'fluttertest-c773f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzCzPs4nlsgbR_ofxXtIxPYA61tmjAVCo',
    appId: '1:796044680835:ios:53eb25ba16fa85024d45b6',
    messagingSenderId: '796044680835',
    projectId: 'fluttertest-c773f',
    storageBucket: 'fluttertest-c773f.firebasestorage.app',
    iosBundleId: 'com.example.flutterTp3Navigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzCzPs4nlsgbR_ofxXtIxPYA61tmjAVCo',
    appId: '1:796044680835:ios:53eb25ba16fa85024d45b6',
    messagingSenderId: '796044680835',
    projectId: 'fluttertest-c773f',
    storageBucket: 'fluttertest-c773f.firebasestorage.app',
    iosBundleId: 'com.example.flutterTp3Navigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCToky06NbY6OQflvzFpPj2gpgJm5Wi3Gw',
    appId: '1:796044680835:web:cf26fac40067bbbb4d45b6',
    messagingSenderId: '796044680835',
    projectId: 'fluttertest-c773f',
    authDomain: 'fluttertest-c773f.firebaseapp.com',
    storageBucket: 'fluttertest-c773f.firebasestorage.app',
  );
}
